[material-fox]
src.github_tag = "muckSponge/MaterialFox"
fetch.github = "muckSponge/MaterialFox"

[arkenfox-userjs]
src.github_tag = "arkenfox/user.js"
fetch.github = "arkenfox/user.js"

[clash-geoip]
src.github_tag = "Dreamacro/maxmind-geoip"
fetch.url = "https://github.com/Dreamacro/maxmind-geoip/releases/download/$ver/Country.mmdb"

[programs-db]
src.cmd = "curl -w '%{url_effective}\n' -I -L -s -S $URL -o /dev/null https://nixos.org/channels/nixos-22.05/nixexprs.tar.xz | grep -o '22\\.05\\.[^/]*'"
fetch.url = "https://releases.nixos.org/nixos/22.05/nixos-$ver/nixexprs.tar.xz"

[yacd]
src.github_tag = "haishanh/yacd"
fetch.url = "https://github.com/haishanh/yacd/releases/download/$ver/yacd.tar.xz"

[ubootPhicommN1]
src.git = "https://github.com/cattyhouse/new-uboot-for-N1.git"
fetch.github = "cattyhouse/new-uboot-for-N1"

## VS Code Extensions

[remote-containers]
src.manual = "0.247.0"
fetch.vsmarketplace = "ms-vscode-remote.remote-containers"
pinned = true

[remote-containers.passthru]
license = "free"
homepage = "https://github.com/Microsoft/vscode-remote-release"
description="Open any folder or repository inside a Docker container."
collection = "vscode-extensions"
publisher = "ms-vscode-remote"
