# This file was generated by nvfetcher, please do not modify it manually.
{ fetchgit, fetchurl, fetchFromGitHub, dockerTools }:
{
  arkenfox-userjs = {
    pname = "arkenfox-userjs";
    version = "112.0";
    src = fetchFromGitHub ({
      owner = "arkenfox";
      repo = "user.js";
      rev = "112.0";
      fetchSubmodules = false;
      sha256 = "sha256-k4PF8FWN6U+//UmZX4UxzBWbfAgEwQznLVsaFV/fVKo=";
    });
  };
  clash-geoip = {
    pname = "clash-geoip";
    version = "20230412";
    src = fetchurl {
      url = "https://github.com/Dreamacro/maxmind-geoip/releases/download/20230412/Country.mmdb";
      sha256 = "sha256-QBHvir5e0JDIYkOouFsPC7SwAQ4fxdUxZcGBWLEUejU=";
    };
  };
  clashctl = {
    pname = "clashctl";
    version = "0.3.3";
    src = fetchurl {
      url = "https://github.com/George-Miao/clashctl/releases/download/0.3.3/clashctl-Linux";
      sha256 = "sha256-Yo26qF0XiWcifJrwbeRcl/a+AsrruZtNaami7cXmNcY=";
    };
  };
  material-fox = {
    pname = "material-fox";
    version = "v93.1";
    src = fetchFromGitHub ({
      owner = "muckSponge";
      repo = "MaterialFox";
      rev = "v93.1";
      fetchSubmodules = false;
      sha256 = "sha256-M20PD3RvkOqZGv4+SzSMGkKdmJ4ZVEDH7WHB4QKFlRw=";
    });
  };
  motrix = {
    pname = "motrix";
    version = "1.8.19";
    src = fetchurl {
      url = "https://github.com/agalwood/Motrix/releases/download/v1.8.19/Motrix-1.8.19.AppImage";
      sha256 = "sha256-oSO+VH3bZcjnXjECqZgOmsvlOONbfgOq50qVLvHdKfo=";
    };
  };
  programs-db = {
    pname = "programs-db";
    version = "22.11.4037.cc45a3f8c98";
    src = fetchurl {
      url = "https://releases.nixos.org/nixos/22.11/nixos-22.11.4037.cc45a3f8c98/nixexprs.tar.xz";
      sha256 = "sha256-tCpD1U78TwZDozPOWqPAmGaskohpRcve2Vb54E/II2w=";
    };
  };
  remote-containers = {
    pname = "remote-containers";
    version = "0.269.0";
    src = fetchurl {
      url = "https://ms-vscode-remote.gallery.vsassets.io/_apis/public/gallery/publisher/ms-vscode-remote/extension/remote-containers/0.269.0/assetbyname/Microsoft.VisualStudio.Services.VSIXPackage";
      name = "remote-containers-0.269.0.zip";
      sha256 = "sha256-8HY46AKbAU5W01BN4iwCUSFqTXfRbC937Gy0kvPTmn4=";
    };
    license = "free";
    homepage = "https://github.com/Microsoft/vscode-remote-release";
    collection = "vscode-extensions";
    description = "Open any folder or repository inside a Docker container.";
    publisher = "ms-vscode-remote";
  };
  ubootPhicommN1 = {
    pname = "ubootPhicommN1";
    version = "9aa890be5f9f4109e1a9a338ab584e0fc9947d5c";
    src = fetchFromGitHub ({
      owner = "cattyhouse";
      repo = "new-uboot-for-N1";
      rev = "9aa890be5f9f4109e1a9a338ab584e0fc9947d5c";
      fetchSubmodules = false;
      sha256 = "sha256-R6lzd7uyAIzxwHph9jZ1y0kTr8kQA5VeCIFyAJMq+vg=";
    });
    date = "2023-04-29";
  };
  yacd = {
    pname = "yacd";
    version = "v0.3.8";
    src = fetchurl {
      url = "https://github.com/haishanh/yacd/releases/download/v0.3.8/yacd.tar.xz";
      sha256 = "sha256-1dfs3pGnCKeThhFnU+MqWfMsjLjuyA3tVsOrlOURulA=";
    };
  };
}
