name: "Build and populate cache"
on:
  push:
    branches:
      - main
      - develop
  pull_request:
  workflow_dispatch:
env:
  nurRepo: slaier
  cachixName: slaier
concurrency:
  group: ${{ github.head_ref || github.ref_name }}
  cancel-in-progress: true
jobs:
  tests:
    strategy:
      matrix:
        nixPath:
          - nixpkgs=channel:nixos-unstable
          - nixpkgs=channel:nixos-22.11
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
      - name: Install nix
        uses: cachix/install-nix-action@v20
        with:
          nix_path: "${{ matrix.nixPath }}"
          extra_nix_config: |
            auto-optimise-store = true
            log-lines = 1000
      - name: Setup cachix
        uses: cachix/cachix-action@v12
        with:
          name: ${{ env.cachixName }}
          authToken: ${{ secrets.CACHIX_AUTH_TOKEN }}
      - name: Check flake evaluation
        run: nix -Lv flake check --show-trace
      - name: Check legacy evaluation
        run: |
          nix-env -f . -qa \* --meta --xml \
            --allowed-uris https://static.rust-lang.org \
            --option restrict-eval true \
            --option allow-import-from-derivation true \
            --drv-path --show-trace \
            -I nixpkgs=$(nix-instantiate --find-file nixpkgs) \
            -I $PWD
      - name: Build nix packages
        run: nix shell -f '<nixpkgs>' nix-build-uncached -c nix-build-uncached ci.nix -A buildOutputs
  update_nur:
    runs-on: ubuntu-latest
    needs: tests
    steps:
      - name: Trigger NUR update
        if: github.ref_protected
        run: curl -XPOST "https://nur-update.nix-community.org/update?repo=${{ env.nurRepo }}"
