name: Update inputs
on:
  push:
    branches:
      - test-*
  schedule:
    # rebuild at 03:39 on Saturday
    - cron:  '39 3 * * 6'
  workflow_dispatch:
jobs:
  update_nix_inputs:
    uses: slaier/reusable-workflows/.github/workflows/update_nix_inputs.yml@test-update-inputs
    with:
      config_path: nvfetcher.toml

