name: Update inputs
on:
  schedule:
    # rebuild at 23:39 on Friday
    - cron:  '39 23 * * 5'
  workflow_dispatch:
jobs:
  update_nix_inputs:
    uses: slaier/reusable-workflows/.github/workflows/update_nix_inputs.yml@main
    with:
      config_path: nvfetcher.toml
    secrets:
      TOKEN: ${{ secrets.PERSONAL_GITHUB_TOKEN }}

